### PR TITLE
allow same name for category in different languages

### PR DESCRIPTION
**Pull request by vasekch**
Dropping unique on Category name and adding unique together for name and language.

This will allow to use the same name for a Alias Category across different languages.

### CODE REVIEW

**Review by fsbraun — APPROVED** [review]
Thank you! Great PR. Let's get this merged!

**Comment by fsbraun** [comment]
@vasekch While at it, can you add the migration from #175 to the migration (also `0003`) here?

**Comment by vasekch** [comment]
@fsbraun thanks for processing this. I realized that there is a forgotten migration in #186 so I've added it. It's a bit clashing.
I first include #175 in here and then leave it up to you which you'll merge first then I'll update the second one (migrations deps).

**Comment by vasekch** [comment]
> ... then leave it up to you which you'll merge first then I'll update the second one (migrations deps).

ok, this should go first and #186 is ready to go right after that

**Pull request merged**
