### PR TITLE
Feature:		Dark mode for djangocms-alias admin

### PR DESCRIPTION
**Pull request by fsbraun**
In accordance with django-cms and djangocms-admin-style the djangocms-alias admin pages can also reflect dark mode.

### CODE REVIEW

**Comment by Aiky30** [comment]
@fsbraun The test suite was not running / needed porting to use github actions. This has now been completed. Can you please merge in the latest changes to your branch?

**Review by Aiky30 — CHANGES_REQUESTED** [review]
As mentioned in my comment the latest changes for the github actions will need to be brought in for these changes. 

Can you also please add screenshots of the light / dark mode fixes to help sign this off?

**Comment by fsbraun** [comment]
w/o dark mode the alias elements stay white:
image

w/ changes in this pr alias elements show same colors as in djangocms-admin-style:
image

**Comment by fsbraun** [comment]
@Aiky30 I added screenshots and have merged the github actions.

**Comment by Aiky30** [comment]
@fsbraun Sadly the admin that you have converted is deprecated. No one has the original designs of how it was supposed to look and feel so it's being replaced by the more conventional versioning table where you have the actions column. You'll see some changes are now present for the versioning admin coming through in version 1.0.x

**Comment by fsbraun** [comment]
@Aiky30 It's in the current master branch. You get there by clicking "Aliases..." in the toolbar. 
Untitled

The versioning's action column will need some tweaks, too, however. They need to be done in djangocms-versioning, I guess. As of Django 3.2 they look like this:
image

Github actions are included. You just need to approve the workflow runs.

**Pull request closed without merging**
